### PR TITLE
[Finishes #157770648] Create CSS Framework

### PR DESCRIPTION
**Pull request by gitaumoses4**
## What does this PR do?
Have a CSS framework to design the pages and ensure consistency in the design.

## Description of Tasks to be completed?
Have the following components
- Row - created using flex
- Container
- Button
- Card
- Dropdown
- Form
- Modal
- Step
- Table 
- Sidebar
- Navbar
- Segment
- Paginator
- Image

## How should this be manually tested?
- Clone the repository into your computer.
```
git clone https://github.com/gitaumoses4/maintenance-tracker
git checkout develop
```
- Navigate to *UI/tests/* and open test.html in your browser. 

## Any background context you want to provide?
The Default font used is [Dosis](https://fonts.google.com/specimen/Dosis)
The UI component design is inspired by [Semantic UI](Https://semantic-ui.com)

## What are the relevant pivotal tracker stories?
[#157770648](https://www.pivotaltracker.com/n/projects/2173234)
# Screenshots 
Framework Components

### CODE REVIEW

**Comment by joelmachango** [comment]
Well documented PR @gitaumoses4

**Comment by maxwellgithinji** [comment]
This is an awesome PR. let me check it out then get back to you.

**Comment by PaulKitonyi** [comment]
Wow.This is so nice @gitaumoses4.Keep the fire burning.

**Comment by zakhusayn** [comment]
Wow!! :+1: Well done Gitau Moses. Well descriptive PR, let alone the design....its amazing

**Pull request merged**
