### PR TITLE
[Finishes #157868188] Create User Signup page

### PR DESCRIPTION
**Pull request by gitaumoses4**
## What does this PR do?
Creates user sign up page.

## Description of task to be completed?
Working sign up page with the following fields:
- First name
- Last name
- Email
- Username 
- Password

## How should this be manually tested?
- Clone the repository into your computer.
```
git clone https://github.com/gitaumoses4/maintenance-tracker
git checkout ft-user-signup-157868188
```
Open the file `UI/register.html` in your browser

## Relevant Pivotal Tracker Stories
[157868188](https://www.pivotaltracker.com/story/show/157868188)

## Screenshots
Sign up

### CODE REVIEW

**Comment by zakhusayn** [comment]
Nice work!

**Comment by johnmusiu** [comment]
Simple and neat UI design, could mistake it for bootstrap, good job

Question: when you write finishes on the PR title does it update PT automatically?

PR structure good

**Comment by gitaumoses4** [comment]
Hello @johnmusiu Thanks for the feedback. Yes, it automatically marks your PT story as finished..

**Comment by asheux** [comment]
I like the UI, it's really cool. Well, structured PR.

**Comment by Slinjez** [comment]
good pr structure and ui design

**Pull request merged**
