### PR TITLE
[Finishes #157895457] Merge to Master

### PR DESCRIPTION
**Pull request by gitaumoses4**
## What does this PR do?
Creates a full web template for the Maintenance Tracker Application

## Description of Tasks to be completed.
1. Users can [create an account](https://gitaumoses4.github.io/maintenance-tracker/UI/register.html) and [log in](https://gitaumoses4.github.io/maintenance-tracker/UI/login.html) 
2. Users should be able to [make maintenance or repair requests](https://gitaumoses4.github.io/maintenance-tracker/UI/user/new-request.html).
3. An admin should be able to [approve/reject](https://gitaumoses4.github.io/maintenance-tracker/UI/admin/request.html) a repair/maintenance request.
4. The admin should be able to [mark a request as resolved](https://gitaumoses4.github.io/maintenance-tracker/UI/admin/request.html) once it is done.
5. The admin should be able to [view all maintenance/repair requests](https://gitaumoses4.github.io/maintenance-tracker/UI/admin/requests.html) on the application.
6. The admin should be able to [filter](https://gitaumoses4.github.io/maintenance-tracker/UI/admin/requests.html) requests.
7. A user can [view all](https://gitaumoses4.github.io/maintenance-tracker/UI/user/requests.html) of his/her requests

## How should this be manually tested?
The template is hosted on [Github Pages](https://gitaumoses4.github.io/maintenance-tracker/)

## What are the relevant Pivotal Tracker Stories
Stories under [Front End](https://www.pivotaltracker.com/epic/show/3976020) epic

## Screenshots
screenshot from 2018-05-26 17-46-41
screenshot from 2018-05-26 17-46-46
screenshot from 2018-05-26 17-46-50
screenshot from 2018-05-26 17-46-57
screenshot from 2018-05-26 17-47-01
screenshot from 2018-05-26 17-47-04
screenshot from 2018-05-26 17-47-08
screenshot from 2018-05-26 17-47-20
screenshot from 2018-05-26 17-47-27
screenshot from 2018-05-26 17-47-31

### CODE REVIEW

**Comment by PaulKitonyi** [comment]
Wow.This so great menh.Well thought UI,PRs and great PT stories.Your UI is reponsvie only that you might have a look at the tables.And if i were to ask who has accepted your PT stories?.

**Comment by gitaumoses4** [comment]
Hey @PaulKitonyi . Thanks alot for the review. I will definitely have a look at the tables.
I accepted the PT stories myself. I think it's because we are the one's evaluating our tasks.

**Comment by PaulKitonyi** [comment]
Okay and Welcome.

**Comment by gtsofa** [comment]
Good job done. Look nice

**Pull request closed without merging**
